/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
    *This form has a scroll bar to select the casino name from the
     * database.  Once the casino is selected, the information of the
     * casino automatically fills in below.

 */
public class CasinoForm extends javax.swing.JFrame {

    /**
     * 
     */
    public CasinoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CasinoNameLabel = new javax.swing.JTextField();
        CasinoNameScroll = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        CasinoID = new javax.swing.JTextField();
        EstablishedDate = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        Street = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        State = new javax.swing.JTextField();
        ZipCode = new javax.swing.JTextField();
        Country = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(448, 251));
        setPreferredSize(new java.awt.Dimension(448, 251));
        getContentPane().setLayout(null);

        CasinoNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        CasinoNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        CasinoNameLabel.setText("Casino Name");
        CasinoNameLabel.setBorder(null);
        CasinoNameLabel.setCaretColor(new java.awt.Color(255, 255, 255));
        CasinoNameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CasinoNameLabel.setOpaque(false);
        CasinoNameLabel.setPreferredSize(new java.awt.Dimension(90, 20));
        CasinoNameLabel.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        CasinoNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasinoNameLabelActionPerformed(evt);
            }
        });
        getContentPane().add(CasinoNameLabel);
        CasinoNameLabel.setBounds(10, 10, 130, 30);

        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CasinoNameScroll.setViewportView(jList1);

        getContentPane().add(CasinoNameScroll);
        CasinoNameScroll.setBounds(150, 20, 80, 146);

        CasinoID.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        CasinoID.setForeground(new java.awt.Color(255, 255, 255));
        CasinoID.setText("Casino ID");
        CasinoID.setBorder(null);
        CasinoID.setOpaque(false);
        CasinoID.setPreferredSize(new java.awt.Dimension(90, 20));
        CasinoID.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(CasinoID);
        CasinoID.setBounds(10, 70, 90, 20);

        EstablishedDate.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        EstablishedDate.setForeground(new java.awt.Color(255, 255, 255));
        EstablishedDate.setText("Established");
        EstablishedDate.setBorder(null);
        EstablishedDate.setOpaque(false);
        EstablishedDate.setPreferredSize(new java.awt.Dimension(90, 20));
        getContentPane().add(EstablishedDate);
        EstablishedDate.setBounds(10, 90, 90, 20);

        PhoneNumber.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        PhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumber.setText("Phone Number");
        PhoneNumber.setBorder(null);
        PhoneNumber.setOpaque(false);
        PhoneNumber.setPreferredSize(new java.awt.Dimension(90, 20));
        PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(PhoneNumber);
        PhoneNumber.setBounds(10, 110, 90, 20);

        Street.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Street.setForeground(new java.awt.Color(255, 255, 255));
        Street.setText("Street ");
        Street.setBorder(null);
        Street.setOpaque(false);
        Street.setPreferredSize(new java.awt.Dimension(90, 20));
        getContentPane().add(Street);
        Street.setBounds(10, 130, 90, 20);

        City.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        City.setForeground(new java.awt.Color(255, 255, 255));
        City.setText("City");
        City.setBorder(null);
        City.setOpaque(false);
        City.setPreferredSize(new java.awt.Dimension(90, 20));
        getContentPane().add(City);
        City.setBounds(10, 150, 90, 20);

        State.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        State.setForeground(new java.awt.Color(255, 255, 255));
        State.setText("State");
        State.setBorder(null);
        State.setOpaque(false);
        State.setPreferredSize(new java.awt.Dimension(90, 20));
        State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateActionPerformed(evt);
            }
        });
        getContentPane().add(State);
        State.setBounds(10, 170, 90, 20);

        ZipCode.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        ZipCode.setForeground(new java.awt.Color(255, 255, 255));
        ZipCode.setText("Zip Code");
        ZipCode.setBorder(null);
        ZipCode.setOpaque(false);
        ZipCode.setPreferredSize(new java.awt.Dimension(90, 20));
        getContentPane().add(ZipCode);
        ZipCode.setBounds(10, 190, 90, 20);

        Country.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Country.setForeground(new java.awt.Color(255, 255, 255));
        Country.setText("Country");
        Country.setBorder(null);
        Country.setOpaque(false);
        Country.setPreferredSize(new java.awt.Dimension(90, 20));
        Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryActionPerformed(evt);
            }
        });
        getContentPane().add(Country);
        Country.setBounds(10, 210, 90, 20);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/448x251.jpg"))); // NOI18N
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 450, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CasinoNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasinoNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasinoNameLabelActionPerformed

    private void StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateActionPerformed

    private void CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryActionPerformed

    private void PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasinoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasinoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasinoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasinoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasinoForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField CasinoID;
    private javax.swing.JTextField CasinoNameLabel;
    private javax.swing.JScrollPane CasinoNameScroll;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField EstablishedDate;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JTextField State;
    private javax.swing.JTextField Street;
    private javax.swing.JTextField ZipCode;
    private javax.swing.JList jList1;
    // End of variables declaration//GEN-END:variables
}
