/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 *The user should be able to enter dates and push the Check Availability button
 * and Yes or No will appear in the Availability area. The casino name will
 * be a drop down box to select the correct casino. Member ID will have to 
 * be filled in.  I am trying to figure out how to load the JCalendar menu
 * to have dates available to select from. Maybe we could remove notes since
 * that may be difficult to format.
 * 
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MemberIDLabel = new javax.swing.JLabel();
        MemberID = new javax.swing.JTextField();
        CheckInDate = new javax.swing.JLabel();
        DateOfCheckIn = new javax.swing.JTextField();
        CheckOutDate = new javax.swing.JLabel();
        DateOfCheckOut = new javax.swing.JTextField();
        CasinoNameLabel = new javax.swing.JTextField();
        CasinoScrollNames = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        CheckAvailability = new javax.swing.JButton();
        AvailableYesNo = new javax.swing.JLabel();
        Notes = new javax.swing.JTextField();
        BackgroundPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MemberIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        MemberIDLabel.setText("Member ID");
        getContentPane().add(MemberIDLabel);
        MemberIDLabel.setBounds(10, 160, 70, 20);

        MemberID.setText("jTextField1");
        getContentPane().add(MemberID);
        MemberID.setBounds(90, 160, 80, 20);

        CheckInDate.setForeground(new java.awt.Color(255, 255, 255));
        CheckInDate.setText("Check-In Date");
        getContentPane().add(CheckInDate);
        CheckInDate.setBounds(10, 190, 80, 20);

        DateOfCheckIn.setText("jTextField1");
        getContentPane().add(DateOfCheckIn);
        DateOfCheckIn.setBounds(90, 190, 80, 20);

        CheckOutDate.setForeground(new java.awt.Color(255, 255, 255));
        CheckOutDate.setText("Check-Out Date");
        getContentPane().add(CheckOutDate);
        CheckOutDate.setBounds(10, 220, 80, 14);

        DateOfCheckOut.setText("jTextField1");
        getContentPane().add(DateOfCheckOut);
        DateOfCheckOut.setBounds(90, 220, 80, 20);

        CasinoNameLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        CasinoNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        CasinoNameLabel.setText("Casino Name");
        CasinoNameLabel.setBorder(null);
        CasinoNameLabel.setCaretColor(new java.awt.Color(255, 255, 255));
        CasinoNameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CasinoNameLabel.setOpaque(false);
        CasinoNameLabel.setPreferredSize(new java.awt.Dimension(90, 20));
        CasinoNameLabel.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        CasinoNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasinoNameLabelActionPerformed(evt);
            }
        });
        getContentPane().add(CasinoNameLabel);
        CasinoNameLabel.setBounds(10, 240, 70, 30);

        CasinoScrollNames.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 224)));
        CasinoScrollNames.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CasinoScrollNames.setViewportView(jList1);

        getContentPane().add(CasinoScrollNames);
        CasinoScrollNames.setBounds(10, 260, 130, 30);

        CheckAvailability.setText("Check Availability");
        CheckAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAvailabilityActionPerformed(evt);
            }
        });
        getContentPane().add(CheckAvailability);
        CheckAvailability.setBounds(190, 150, 140, 23);

        AvailableYesNo.setForeground(new java.awt.Color(255, 255, 255));
        AvailableYesNo.setText("Avalable");
        getContentPane().add(AvailableYesNo);
        AvailableYesNo.setBounds(340, 150, 50, 20);

        Notes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Notes.setText("Notes:");
        Notes.setCaretColor(new java.awt.Color(255, 255, 255));
        Notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesActionPerformed(evt);
            }
        });
        getContentPane().add(Notes);
        Notes.setBounds(190, 180, 200, 70);

        BackgroundPic.setIcon(new javax.swing.ImageIcon("C:\\Users\\hillman\\Desktop\\hotel room resized.jpg")); // NOI18N
        getContentPane().add(BackgroundPic);
        BackgroundPic.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CasinoNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasinoNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasinoNameLabelActionPerformed

    private void NotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotesActionPerformed

    private void CheckAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckAvailabilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rooms().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvailableYesNo;
    private javax.swing.JLabel BackgroundPic;
    private javax.swing.JTextField CasinoNameLabel;
    private javax.swing.JScrollPane CasinoScrollNames;
    private javax.swing.JButton CheckAvailability;
    private javax.swing.JLabel CheckInDate;
    private javax.swing.JLabel CheckOutDate;
    private javax.swing.JTextField DateOfCheckIn;
    private javax.swing.JTextField DateOfCheckOut;
    private javax.swing.JTextField MemberID;
    private javax.swing.JLabel MemberIDLabel;
    private javax.swing.JTextField Notes;
    private javax.swing.JList jList1;
    // End of variables declaration//GEN-END:variables
}
