/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 *This is a background available for other pages.
 *
 *
 */
public class Spa extends javax.swing.JFrame {

    /**
     * Creates new form Spa
     */
    public Spa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MemberIDLabel = new javax.swing.JLabel();
        MemberID = new javax.swing.JTextField();
        DateOfService = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        TimeOfService = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        TreatmentLabel = new javax.swing.JLabel();
        TreatmentList = new javax.swing.JScrollPane();
        Facial = new javax.swing.JList();
        CasinoNameLabel = new javax.swing.JTextField();
        CasinoScrollNames = new javax.swing.JScrollPane();
        CasinoList = new javax.swing.JList();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MemberIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        MemberIDLabel.setText("Member ID");
        getContentPane().add(MemberIDLabel);
        MemberIDLabel.setBounds(50, 10, 70, 20);

        MemberID.setText("jTextField1");
        getContentPane().add(MemberID);
        MemberID.setBounds(110, 10, 80, 20);

        DateOfService.setForeground(new java.awt.Color(255, 255, 255));
        DateOfService.setText("Date Of Service");
        getContentPane().add(DateOfService);
        DateOfService.setBounds(30, 40, 90, 20);

        Date.setText("jTextField1");
        getContentPane().add(Date);
        Date.setBounds(280, 40, 80, 20);

        TimeOfService.setForeground(new java.awt.Color(255, 255, 255));
        TimeOfService.setText("Time Of Service");
        getContentPane().add(TimeOfService);
        TimeOfService.setBounds(200, 40, 90, 20);

        Time.setText("jTextField1");
        getContentPane().add(Time);
        Time.setBounds(110, 40, 80, 20);

        TreatmentLabel.setForeground(new java.awt.Color(255, 255, 255));
        TreatmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TreatmentLabel.setText("Treatment");
        getContentPane().add(TreatmentLabel);
        TreatmentLabel.setBounds(34, 70, 70, 20);

        Facial.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        TreatmentList.setViewportView(Facial);

        getContentPane().add(TreatmentList);
        TreatmentList.setBounds(110, 70, 80, 80);

        CasinoNameLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        CasinoNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        CasinoNameLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CasinoNameLabel.setText("Casino Name");
        CasinoNameLabel.setBorder(null);
        CasinoNameLabel.setCaretColor(new java.awt.Color(255, 255, 255));
        CasinoNameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CasinoNameLabel.setOpaque(false);
        CasinoNameLabel.setPreferredSize(new java.awt.Dimension(90, 20));
        CasinoNameLabel.setSelectedTextColor(new java.awt.Color(255, 0, 0));
        CasinoNameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasinoNameLabelActionPerformed(evt);
            }
        });
        getContentPane().add(CasinoNameLabel);
        CasinoNameLabel.setBounds(10, 150, 120, 30);

        CasinoScrollNames.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 224)));
        CasinoScrollNames.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CasinoList.setForeground(new java.awt.Color(255, 255, 255));
        CasinoList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CasinoScrollNames.setViewportView(CasinoList);

        getContentPane().add(CasinoScrollNames);
        CasinoScrollNames.setBounds(90, 160, 100, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/spa4resized.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 400, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CasinoNameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasinoNameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasinoNameLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JList CasinoList;
    private javax.swing.JTextField CasinoNameLabel;
    private javax.swing.JScrollPane CasinoScrollNames;
    private javax.swing.JTextField Date;
    private javax.swing.JLabel DateOfService;
    private javax.swing.JList Facial;
    private javax.swing.JTextField MemberID;
    private javax.swing.JLabel MemberIDLabel;
    private javax.swing.JTextField Time;
    private javax.swing.JLabel TimeOfService;
    private javax.swing.JLabel TreatmentLabel;
    private javax.swing.JScrollPane TreatmentList;
    // End of variables declaration//GEN-END:variables
}
