/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Casino;

/**
 *This page will be the first page.  The menu tabs on top
 * will connect to the various input pages.  
 * 
 */
public class MenuPage extends javax.swing.JFrame {

    /**
     * Creates new form MenuPage
     */
    public MenuPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Member = new javax.swing.JMenu();
        Casino = new javax.swing.JMenu();
        Rooms = new javax.swing.JMenu();
        Restaurant = new javax.swing.JMenu();
        Device = new javax.swing.JMenu();
        Spa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casino/448x251.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 448, 251);

        Member.setText("Member");
        jMenuBar1.add(Member);

        Casino.setText("Casino");
        Casino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasinoActionPerformed(evt);
            }
        });
        jMenuBar1.add(Casino);

        Rooms.setText("Rooms");
        Rooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsActionPerformed(evt);
            }
        });
        jMenuBar1.add(Rooms);

        Restaurant.setText("Restaurant");
        Restaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaurantActionPerformed(evt);
            }
        });
        jMenuBar1.add(Restaurant);

        Device.setText("Device");
        Device.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeviceActionPerformed(evt);
            }
        });
        jMenuBar1.add(Device);

        Spa.setText("Spa");
        Spa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaActionPerformed(evt);
            }
        });
        jMenuBar1.add(Spa);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CasinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasinoActionPerformed

    private void RoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomsActionPerformed

    private void RestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaurantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RestaurantActionPerformed

    private void DeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeviceActionPerformed

    private void SpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JMenu Casino;
    private javax.swing.JMenu Device;
    private javax.swing.JMenu Member;
    private javax.swing.JMenu Restaurant;
    private javax.swing.JMenu Rooms;
    private javax.swing.JMenu Spa;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
